// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchants.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (merchant_id, name, email)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, name, email, status, created_at, updated_at
`

type CreateMerchantParams struct {
	MerchantID string `db:"merchant_id" json:"merchant_id"`
	Name       string `db:"name" json:"name"`
	Email      string `db:"email" json:"email"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg *CreateMerchantParams) (*Merchant, error) {
	row := q.db.QueryRowContext(ctx, createMerchant, arg.MerchantID, arg.Name, arg.Email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createMerchantAPIKey = `-- name: CreateMerchantAPIKey :one
INSERT INTO merchant_api_keys (merchant_id, api_key, secret_key)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, api_key, status, created_at, expires_at
`

type CreateMerchantAPIKeyParams struct {
	MerchantID uuid.UUID `db:"merchant_id" json:"merchant_id"`
	ApiKey     string    `db:"api_key" json:"api_key"`
	SecretKey  string    `db:"secret_key" json:"secret_key"`
}

type CreateMerchantAPIKeyRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	MerchantID uuid.UUID        `db:"merchant_id" json:"merchant_id"`
	ApiKey     string           `db:"api_key" json:"api_key"`
	Status     NullApiKeyStatus `db:"status" json:"status"`
	CreatedAt  sql.NullTime     `db:"created_at" json:"created_at"`
	ExpiresAt  sql.NullTime     `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateMerchantAPIKey(ctx context.Context, arg *CreateMerchantAPIKeyParams) (*CreateMerchantAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createMerchantAPIKey, arg.MerchantID, arg.ApiKey, arg.SecretKey)
	var i CreateMerchantAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ApiKey,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, email, status, created_at, updated_at
FROM merchants
WHERE id = $1
`

type GetMerchantRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Status    NullMerchantStatus `db:"status" json:"status"`
	CreatedAt sql.NullTime       `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMerchant(ctx context.Context, id uuid.UUID) (*GetMerchantRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchant, id)
	var i GetMerchantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantByAPIKey = `-- name: GetMerchantByAPIKey :one
SELECT m.id, m.name, m.email, m.status, m.created_at, m.updated_at
FROM merchants m
JOIN merchant_api_keys mak ON m.id = mak.merchant_id
WHERE mak.api_key = $1 AND mak.status = 'active' AND m.status = 'active'
`

type GetMerchantByAPIKeyRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Status    NullMerchantStatus `db:"status" json:"status"`
	CreatedAt sql.NullTime       `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMerchantByAPIKey(ctx context.Context, apiKey string) (*GetMerchantByAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByAPIKey, apiKey)
	var i GetMerchantByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantByAPIKeyValue = `-- name: GetMerchantByAPIKeyValue :one
SELECT m.id, m.merchant_id, m.name, m.email, m.status, m.created_at, m.updated_at,
       mak.api_key, mak.secret_key, mak.status as api_key_status, mak.created_at as api_key_created_at
FROM merchants m
JOIN merchant_api_keys mak ON m.id = mak.merchant_id
WHERE mak.api_key = $1 AND mak.status = 'active' AND m.status = 'active'
`

type GetMerchantByAPIKeyValueRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	MerchantID      string             `db:"merchant_id" json:"merchant_id"`
	Name            string             `db:"name" json:"name"`
	Email           string             `db:"email" json:"email"`
	Status          NullMerchantStatus `db:"status" json:"status"`
	CreatedAt       sql.NullTime       `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime       `db:"updated_at" json:"updated_at"`
	ApiKey          string             `db:"api_key" json:"api_key"`
	SecretKey       string             `db:"secret_key" json:"secret_key"`
	ApiKeyStatus    NullApiKeyStatus   `db:"api_key_status" json:"api_key_status"`
	ApiKeyCreatedAt sql.NullTime       `db:"api_key_created_at" json:"api_key_created_at"`
}

func (q *Queries) GetMerchantByAPIKeyValue(ctx context.Context, apiKey string) (*GetMerchantByAPIKeyValueRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByAPIKeyValue, apiKey)
	var i GetMerchantByAPIKeyValueRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
		&i.SecretKey,
		&i.ApiKeyStatus,
		&i.ApiKeyCreatedAt,
	)
	return &i, err
}

const getMerchantByMerchantID = `-- name: GetMerchantByMerchantID :one
SELECT id, merchant_id, name, email, status, created_at, updated_at
FROM merchants
WHERE merchant_id = $1
`

func (q *Queries) GetMerchantByMerchantID(ctx context.Context, merchantID string) (*Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByMerchantID, merchantID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantWithAPIKey = `-- name: GetMerchantWithAPIKey :one
SELECT m.id, m.merchant_id, m.name, m.email, m.status, m.created_at, m.updated_at,
       mak.api_key, mak.secret_key, mak.status as api_key_status, mak.created_at as api_key_created_at
FROM merchants m
JOIN merchant_api_keys mak ON m.id = mak.merchant_id
WHERE m.merchant_id = $1 AND mak.status = 'active'
`

type GetMerchantWithAPIKeyRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	MerchantID      string             `db:"merchant_id" json:"merchant_id"`
	Name            string             `db:"name" json:"name"`
	Email           string             `db:"email" json:"email"`
	Status          NullMerchantStatus `db:"status" json:"status"`
	CreatedAt       sql.NullTime       `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime       `db:"updated_at" json:"updated_at"`
	ApiKey          string             `db:"api_key" json:"api_key"`
	SecretKey       string             `db:"secret_key" json:"secret_key"`
	ApiKeyStatus    NullApiKeyStatus   `db:"api_key_status" json:"api_key_status"`
	ApiKeyCreatedAt sql.NullTime       `db:"api_key_created_at" json:"api_key_created_at"`
}

func (q *Queries) GetMerchantWithAPIKey(ctx context.Context, merchantID string) (*GetMerchantWithAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantWithAPIKey, merchantID)
	var i GetMerchantWithAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
		&i.SecretKey,
		&i.ApiKeyStatus,
		&i.ApiKeyCreatedAt,
	)
	return &i, err
}
