// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchants.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (name, email)
VALUES ($1, $2)
RETURNING id, name, email, status, created_at, updated_at
`

type CreateMerchantParams struct {
	Name  string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg *CreateMerchantParams) (*Merchant, error) {
	row := q.db.QueryRowContext(ctx, createMerchant, arg.Name, arg.Email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createMerchantAPIKey = `-- name: CreateMerchantAPIKey :one
INSERT INTO merchant_api_keys (merchant_id, api_key, secret_key)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, api_key, status, created_at, expires_at
`

type CreateMerchantAPIKeyParams struct {
	MerchantID uuid.UUID `db:"merchant_id" json:"merchant_id"`
	ApiKey     string    `db:"api_key" json:"api_key"`
	SecretKey  string    `db:"secret_key" json:"secret_key"`
}

type CreateMerchantAPIKeyRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	MerchantID uuid.UUID        `db:"merchant_id" json:"merchant_id"`
	ApiKey     string           `db:"api_key" json:"api_key"`
	Status     NullApiKeyStatus `db:"status" json:"status"`
	CreatedAt  sql.NullTime     `db:"created_at" json:"created_at"`
	ExpiresAt  sql.NullTime     `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateMerchantAPIKey(ctx context.Context, arg *CreateMerchantAPIKeyParams) (*CreateMerchantAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createMerchantAPIKey, arg.MerchantID, arg.ApiKey, arg.SecretKey)
	var i CreateMerchantAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ApiKey,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, email, status, created_at, updated_at
FROM merchants
WHERE id = $1
`

func (q *Queries) GetMerchant(ctx context.Context, id uuid.UUID) (*Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantByAPIKey = `-- name: GetMerchantByAPIKey :one
SELECT m.id, m.name, m.email, m.status, m.created_at, m.updated_at
FROM merchants m
JOIN merchant_api_keys mak ON m.id = mak.merchant_id
WHERE mak.api_key = $1 AND mak.status = 'active' AND m.status = 'active'
`

func (q *Queries) GetMerchantByAPIKey(ctx context.Context, apiKey string) (*Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByAPIKey, apiKey)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
