// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiKeyStatus string

const (
	ApiKeyStatusActive   ApiKeyStatus = "active"
	ApiKeyStatusInactive ApiKeyStatus = "inactive"
	ApiKeyStatusExpired  ApiKeyStatus = "expired"
)

func (e *ApiKeyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiKeyStatus(s)
	case string:
		*e = ApiKeyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiKeyStatus: %T", src)
	}
	return nil
}

type NullApiKeyStatus struct {
	ApiKeyStatus ApiKeyStatus `json:"api_key_status"`
	Valid        bool         `json:"valid"` // Valid is true if ApiKeyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiKeyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApiKeyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiKeyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiKeyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiKeyStatus), nil
}

func (e ApiKeyStatus) Valid() bool {
	switch e {
	case ApiKeyStatusActive,
		ApiKeyStatusInactive,
		ApiKeyStatusExpired:
		return true
	}
	return false
}

func AllApiKeyStatusValues() []ApiKeyStatus {
	return []ApiKeyStatus{
		ApiKeyStatusActive,
		ApiKeyStatusInactive,
		ApiKeyStatusExpired,
	}
}

type CurrencyType string

const (
	CurrencyTypeETB CurrencyType = "ETB"
	CurrencyTypeUSD CurrencyType = "USD"
)

func (e *CurrencyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrencyType(s)
	case string:
		*e = CurrencyType(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrencyType: %T", src)
	}
	return nil
}

type NullCurrencyType struct {
	CurrencyType CurrencyType `json:"currency_type"`
	Valid        bool         `json:"valid"` // Valid is true if CurrencyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrencyType) Scan(value interface{}) error {
	if value == nil {
		ns.CurrencyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrencyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrencyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrencyType), nil
}

func (e CurrencyType) Valid() bool {
	switch e {
	case CurrencyTypeETB,
		CurrencyTypeUSD:
		return true
	}
	return false
}

func AllCurrencyTypeValues() []CurrencyType {
	return []CurrencyType{
		CurrencyTypeETB,
		CurrencyTypeUSD,
	}
}

type EventType string

const (
	EventTypeCreated    EventType = "created"
	EventTypeProcessing EventType = "processing"
	EventTypeCompleted  EventType = "completed"
	EventTypeFailed     EventType = "failed"
	EventTypeCancelled  EventType = "cancelled"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType `json:"event_type"`
	Valid     bool      `json:"valid"` // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

func (e EventType) Valid() bool {
	switch e {
	case EventTypeCreated,
		EventTypeProcessing,
		EventTypeCompleted,
		EventTypeFailed,
		EventTypeCancelled:
		return true
	}
	return false
}

func AllEventTypeValues() []EventType {
	return []EventType{
		EventTypeCreated,
		EventTypeProcessing,
		EventTypeCompleted,
		EventTypeFailed,
		EventTypeCancelled,
	}
}

type MerchantStatus string

const (
	MerchantStatusActive    MerchantStatus = "active"
	MerchantStatusInactive  MerchantStatus = "inactive"
	MerchantStatusSuspended MerchantStatus = "suspended"
)

func (e *MerchantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MerchantStatus(s)
	case string:
		*e = MerchantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MerchantStatus: %T", src)
	}
	return nil
}

type NullMerchantStatus struct {
	MerchantStatus MerchantStatus `json:"merchant_status"`
	Valid          bool           `json:"valid"` // Valid is true if MerchantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMerchantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MerchantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MerchantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMerchantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MerchantStatus), nil
}

func (e MerchantStatus) Valid() bool {
	switch e {
	case MerchantStatusActive,
		MerchantStatusInactive,
		MerchantStatusSuspended:
		return true
	}
	return false
}

func AllMerchantStatusValues() []MerchantStatus {
	return []MerchantStatus{
		MerchantStatusActive,
		MerchantStatusInactive,
		MerchantStatusSuspended,
	}
}

type PaymentMethodType string

const (
	PaymentMethodTypeCard         PaymentMethodType = "card"
	PaymentMethodTypeBankTransfer PaymentMethodType = "bank_transfer"
	PaymentMethodTypeMobileMoney  PaymentMethodType = "mobile_money"
	PaymentMethodTypeCbe          PaymentMethodType = "cbe"
	PaymentMethodTypeMpesa        PaymentMethodType = "mpesa"
	PaymentMethodTypeTelebirr     PaymentMethodType = "telebirr"
	PaymentMethodTypeAwash        PaymentMethodType = "awash"
)

func (e *PaymentMethodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethodType(s)
	case string:
		*e = PaymentMethodType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethodType: %T", src)
	}
	return nil
}

type NullPaymentMethodType struct {
	PaymentMethodType PaymentMethodType `json:"payment_method_type"`
	Valid             bool              `json:"valid"` // Valid is true if PaymentMethodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethodType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethodType), nil
}

func (e PaymentMethodType) Valid() bool {
	switch e {
	case PaymentMethodTypeCard,
		PaymentMethodTypeBankTransfer,
		PaymentMethodTypeMobileMoney,
		PaymentMethodTypeCbe,
		PaymentMethodTypeMpesa,
		PaymentMethodTypeTelebirr,
		PaymentMethodTypeAwash:
		return true
	}
	return false
}

func AllPaymentMethodTypeValues() []PaymentMethodType {
	return []PaymentMethodType{
		PaymentMethodTypeCard,
		PaymentMethodTypeBankTransfer,
		PaymentMethodTypeMobileMoney,
		PaymentMethodTypeCbe,
		PaymentMethodTypeMpesa,
		PaymentMethodTypeTelebirr,
		PaymentMethodTypeAwash,
	}
}

type PaymentStatus string

const (
	PaymentStatusPending    PaymentStatus = "pending"
	PaymentStatusProcessing PaymentStatus = "processing"
	PaymentStatusSuccess    PaymentStatus = "success"
	PaymentStatusFailed     PaymentStatus = "failed"
	PaymentStatusCancelled  PaymentStatus = "cancelled"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusPending,
		PaymentStatusProcessing,
		PaymentStatusSuccess,
		PaymentStatusFailed,
		PaymentStatusCancelled:
		return true
	}
	return false
}

func AllPaymentStatusValues() []PaymentStatus {
	return []PaymentStatus{
		PaymentStatusPending,
		PaymentStatusProcessing,
		PaymentStatusSuccess,
		PaymentStatusFailed,
		PaymentStatusCancelled,
	}
}

type TransactionStatus string

const (
	TransactionStatusPending TransactionStatus = "pending"
	TransactionStatusSuccess TransactionStatus = "success"
	TransactionStatusFailed  TransactionStatus = "failed"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

func (e TransactionStatus) Valid() bool {
	switch e {
	case TransactionStatusPending,
		TransactionStatusSuccess,
		TransactionStatusFailed:
		return true
	}
	return false
}

func AllTransactionStatusValues() []TransactionStatus {
	return []TransactionStatus{
		TransactionStatusPending,
		TransactionStatusSuccess,
		TransactionStatusFailed,
	}
}

type Merchant struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	MerchantID string             `db:"merchant_id" json:"merchant_id"`
	Name       string             `db:"name" json:"name"`
	Email      string             `db:"email" json:"email"`
	Status     NullMerchantStatus `db:"status" json:"status"`
	CreatedAt  sql.NullTime       `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime       `db:"updated_at" json:"updated_at"`
}

type MerchantApiKey struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	MerchantID uuid.UUID        `db:"merchant_id" json:"merchant_id"`
	ApiKey     string           `db:"api_key" json:"api_key"`
	SecretKey  string           `db:"secret_key" json:"secret_key"`
	Status     NullApiKeyStatus `db:"status" json:"status"`
	CreatedAt  sql.NullTime     `db:"created_at" json:"created_at"`
	ExpiresAt  sql.NullTime     `db:"expires_at" json:"expires_at"`
}

type MerchantBalance struct {
	ID                    uuid.UUID      `db:"id" json:"id"`
	MerchantID            uuid.UUID      `db:"merchant_id" json:"merchant_id"`
	Currency              CurrencyType   `db:"currency" json:"currency"`
	AvailableBalance      sql.NullString `db:"available_balance" json:"available_balance"`
	TotalDeposit          sql.NullString `db:"total_deposit" json:"total_deposit"`
	TotalTransactionCount sql.NullInt32  `db:"total_transaction_count" json:"total_transaction_count"`
	LastUpdated           sql.NullTime   `db:"last_updated" json:"last_updated"`
}

type PaymentIntent struct {
	ID              uuid.UUID             `db:"id" json:"id"`
	PaymentIntentID string                `db:"payment_intent_id" json:"payment_intent_id"`
	MerchantID      string                `db:"merchant_id" json:"merchant_id"`
	Amount          string                `db:"amount" json:"amount"`
	Currency        string                `db:"currency" json:"currency"`
	Status          NullPaymentStatus     `db:"status" json:"status"`
	Description     sql.NullString        `db:"description" json:"description"`
	CallbackUrl     string                `db:"callback_url" json:"callback_url"`
	Nonce           string                `db:"nonce" json:"nonce"`
	Metadata        pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	CreatedAt       sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt       sql.NullTime          `db:"updated_at" json:"updated_at"`
	ExpiresAt       sql.NullTime          `db:"expires_at" json:"expires_at"`
}

type PaymentTransaction struct {
	ID                  uuid.UUID             `db:"id" json:"id"`
	PaymentIntentID     string                `db:"payment_intent_id" json:"payment_intent_id"`
	MerchantID          string                `db:"merchant_id" json:"merchant_id"`
	Amount              string                `db:"amount" json:"amount"`
	Currency            CurrencyType          `db:"currency" json:"currency"`
	Status              NullTransactionStatus `db:"status" json:"status"`
	ThirdPartyReference sql.NullString        `db:"third_party_reference" json:"third_party_reference"`
	PaymentMethod       NullPaymentMethodType `db:"payment_method" json:"payment_method"`
	FeeAmount           sql.NullString        `db:"fee_amount" json:"fee_amount"`
	AccountNumber       sql.NullString        `db:"account_number" json:"account_number"`
	ProcessedAt         sql.NullTime          `db:"processed_at" json:"processed_at"`
	CreatedAt           sql.NullTime          `db:"created_at" json:"created_at"`
	UpdatedAt           sql.NullTime          `db:"updated_at" json:"updated_at"`
}
