// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_intents (transaction_id, merchant_id, amount, currency, reference, callback_url, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, transaction_id, merchant_id, amount, currency, reference, callback_url, status, metadata, created_at, updated_at, expires_at
`

type CreatePaymentIntentParams struct {
	TransactionID string                `db:"transaction_id" json:"transaction_id"`
	MerchantID    uuid.UUID             `db:"merchant_id" json:"merchant_id"`
	Amount        string                `db:"amount" json:"amount"`
	Currency      CurrencyType          `db:"currency" json:"currency"`
	Reference     string                `db:"reference" json:"reference"`
	CallbackUrl   string                `db:"callback_url" json:"callback_url"`
	Metadata      pqtype.NullRawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg *CreatePaymentIntentParams) (*PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, createPaymentIntent,
		arg.TransactionID,
		arg.MerchantID,
		arg.Amount,
		arg.Currency,
		arg.Reference,
		arg.CallbackUrl,
		arg.Metadata,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.CallbackUrl,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (transaction_id, payment_intent_id, merchant_id, amount, currency, payment_method)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, payment_intent_id, merchant_id, amount, currency, status, third_party_reference, payment_method, fee_amount, processed_at, created_at, updated_at
`

type CreatePaymentTransactionParams struct {
	TransactionID   string                `db:"transaction_id" json:"transaction_id"`
	PaymentIntentID uuid.UUID             `db:"payment_intent_id" json:"payment_intent_id"`
	MerchantID      uuid.UUID             `db:"merchant_id" json:"merchant_id"`
	Amount          string                `db:"amount" json:"amount"`
	Currency        CurrencyType          `db:"currency" json:"currency"`
	PaymentMethod   NullPaymentMethodType `db:"payment_method" json:"payment_method"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg *CreatePaymentTransactionParams) (*PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, createPaymentTransaction,
		arg.TransactionID,
		arg.PaymentIntentID,
		arg.MerchantID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.PaymentIntentID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ThirdPartyReference,
		&i.PaymentMethod,
		&i.FeeAmount,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaymentIntent = `-- name: GetPaymentIntent :one
SELECT id, transaction_id, merchant_id, amount, currency, reference, callback_url, status, metadata, created_at, updated_at, expires_at
FROM payment_intents
WHERE transaction_id = $1
`

func (q *Queries) GetPaymentIntent(ctx context.Context, transactionID string) (*PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, getPaymentIntent, transactionID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.CallbackUrl,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const getPaymentIntentByID = `-- name: GetPaymentIntentByID :one
SELECT id, transaction_id, merchant_id, amount, currency, reference, callback_url, status, metadata, created_at, updated_at, expires_at
FROM payment_intents
WHERE id = $1
`

func (q *Queries) GetPaymentIntentByID(ctx context.Context, id uuid.UUID) (*PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, getPaymentIntentByID, id)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.CallbackUrl,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const getPaymentTransaction = `-- name: GetPaymentTransaction :one
SELECT id, transaction_id, payment_intent_id, merchant_id, amount, currency, status, third_party_reference, payment_method, fee_amount, processed_at, created_at, updated_at
FROM payment_transactions
WHERE transaction_id = $1
`

func (q *Queries) GetPaymentTransaction(ctx context.Context, transactionID string) (*PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, getPaymentTransaction, transactionID)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.PaymentIntentID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ThirdPartyReference,
		&i.PaymentMethod,
		&i.FeeAmount,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePaymentIntentStatus = `-- name: UpdatePaymentIntentStatus :one
UPDATE payment_intents
SET status = $2, updated_at = NOW()
WHERE id = $1 AND status = $3
RETURNING id, transaction_id, merchant_id, amount, currency, reference, callback_url, status, metadata, created_at, updated_at, expires_at
`

type UpdatePaymentIntentStatusParams struct {
	ID       uuid.UUID         `db:"id" json:"id"`
	Status   NullPaymentStatus `db:"status" json:"status"`
	Status_2 NullPaymentStatus `db:"status_2" json:"status_2"`
}

func (q *Queries) UpdatePaymentIntentStatus(ctx context.Context, arg *UpdatePaymentIntentStatusParams) (*PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentIntentStatus, arg.ID, arg.Status, arg.Status_2)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.CallbackUrl,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const updatePaymentTransactionStatus = `-- name: UpdatePaymentTransactionStatus :one
UPDATE payment_transactions
SET status = $2, third_party_reference = $3, processed_at = NOW(), updated_at = NOW()
WHERE transaction_id = $1 AND status = $4
RETURNING id, transaction_id, payment_intent_id, merchant_id, amount, currency, status, third_party_reference, payment_method, fee_amount, processed_at, created_at, updated_at
`

type UpdatePaymentTransactionStatusParams struct {
	TransactionID       string                `db:"transaction_id" json:"transaction_id"`
	Status              NullTransactionStatus `db:"status" json:"status"`
	ThirdPartyReference sql.NullString        `db:"third_party_reference" json:"third_party_reference"`
	Status_2            NullTransactionStatus `db:"status_2" json:"status_2"`
}

func (q *Queries) UpdatePaymentTransactionStatus(ctx context.Context, arg *UpdatePaymentTransactionStatusParams) (*PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentTransactionStatus,
		arg.TransactionID,
		arg.Status,
		arg.ThirdPartyReference,
		arg.Status_2,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.PaymentIntentID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ThirdPartyReference,
		&i.PaymentMethod,
		&i.FeeAmount,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
